### ISSUE TITLE
Unrecognized property 'enabled'

### ISSUE THREAD

**Issue by staff0rd** [go-dima/serverless-plugin-conditional-functions#5]
Hiya! This plugin works, but during deployment I get the following warning:

> Serverless: Configuration warning:
> Serverless:   at 'functions.nameOfMyFunction': unrecognized property 'enabled'

**Comment by arrohhdoublebee** [comment]
Looks to have been fixed as of https://github.com/go-dima/serverless-plugin-conditional-functions/commit/39ffd32e8d52ad47c8401f038ce66431f4dbbed1, but hasn't been released yet

**Comment by Maxwell2022** [comment]
We are using `configValidationMode: error` so we are not able to use this plugin as is. 
Would it be possible to release this? cc @go-dima, @adam-skalicky

**Comment by go-dima** [comment]
Hi guys,

I published v1.0.1 with @adam-skalicky (🥇  thanks for your contribution!) change. There is an issue with the tests which I will fix shortly.

I'm glad you find this plugin useful :)

**Comment by go-dima** [comment]
Solved in PR #4, new version published.
